repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: "v8.2.0"
  #   hooks:
  #     - id: eslint
  #       args: [--fix]
  #       files: \.[jt]sx?$
  #       types: [file]

  - repo: local
    hooks:
      - id: build
        name: Build Node Project
        description: Ensure project can build properly
        language: system
        entry: bash -c 'npm run build'
        types: [javascript, jsx, ts, tsx]
        pass_filenames: false
        always_run: true
